// <auto-generated />
namespace ApiModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AceptacionFacturas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AceptacionFacturas));
        
        string IMigrationMetadata.Id
        {
            get { return "201810020042033_AceptacionFacturas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
