// <auto-generated />
namespace ApiModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class productoimpuesto_deleteCascade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productoimpuesto_deleteCascade));
        
        string IMigrationMetadata.Id
        {
            get { return "201808130107234_productoimpuesto_deleteCascade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
