// <auto-generated />
namespace ApiModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nuevoscampos43 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nuevoscampos43));
        
        string IMigrationMetadata.Id
        {
            get { return "201907170014381_nuevoscampos43"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
