//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.6.1055.0.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeReceptor")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeReceptor", IsNullable=false)]
public partial class MensajeReceptor {
    
    private string claveField;
    
    private string numeroCedulaEmisorField;
    
    private System.DateTime fechaEmisionDocField;
    
    private MensajeReceptorMensaje mensajeField;
    
    private string detalleMensajeField;
    
    private decimal montoTotalImpuestoField;
    
    private bool montoTotalImpuestoFieldSpecified;
    
    private decimal totalFacturaField;
    
    private string numeroCedulaReceptorField;
    
    private string numeroConsecutivoReceptorField;
    
    /// <comentarios/>
    public string Clave {
        get {
            return this.claveField;
        }
        set {
            this.claveField = value;
        }
    }
    
    /// <comentarios/>
    public string NumeroCedulaEmisor {
        get {
            return this.numeroCedulaEmisorField;
        }
        set {
            this.numeroCedulaEmisorField = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime FechaEmisionDoc {
        get {
            return this.fechaEmisionDocField;
        }
        set {
            this.fechaEmisionDocField = value;
        }
    }
    
    /// <comentarios/>
    public MensajeReceptorMensaje Mensaje {
        get {
            return this.mensajeField;
        }
        set {
            this.mensajeField = value;
        }
    }
    
    /// <comentarios/>
    public string DetalleMensaje {
        get {
            return this.detalleMensajeField;
        }
        set {
            this.detalleMensajeField = value;
        }
    }
    
    /// <comentarios/>
    public decimal MontoTotalImpuesto {
        get {
            return this.montoTotalImpuestoField;
        }
        set {
            this.montoTotalImpuestoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MontoTotalImpuestoSpecified {
        get {
            return this.montoTotalImpuestoFieldSpecified;
        }
        set {
            this.montoTotalImpuestoFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public decimal TotalFactura {
        get {
            return this.totalFacturaField;
        }
        set {
            this.totalFacturaField = value;
        }
    }
    
    /// <comentarios/>
    public string NumeroCedulaReceptor {
        get {
            return this.numeroCedulaReceptorField;
        }
        set {
            this.numeroCedulaReceptorField = value;
        }
    }
    
    /// <comentarios/>
    public string NumeroConsecutivoReceptor {
        get {
            return this.numeroConsecutivoReceptorField;
        }
        set {
            this.numeroConsecutivoReceptorField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeReceptor")]
public enum MensajeReceptorMensaje {
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}
